# Generated by Django 4.1.7 on 2023-04-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
