# Generated by Django 4.1.7 on 2023-04-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_portal_settings_alter_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='unknownCourse', max_length=255),
        ),
        migrations.AddField(
            model_name='portal',
            name='name',
            field=models.CharField(default='unknownPortal', max_length=255),
        ),
        migrations.AddField(
            model_name='portal',
            name='token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portal',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='botToken',
            field=models.TextField(blank=True),
        ),
    ]
