# Generated by Django 4.1.7 on 2023-04-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_course_name_portal_name_portal_token_portal_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='notDefined', max_length=255),
        ),
    ]
