# Generated by Django 4.1.7 on 2023-04-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_question_answer_alter_question_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='portal',
            field=models.CharField(default='notKnown', max_length=255),
        ),
    ]
